.ORIG x3000
TRAP 0x29 ; get player position

;CHECKS X COOR
ADD R0 R0 #0
BRn NEGX ;CHECKS IF NEGATIVE
JSR POSITIVE_X
BRnzp SKIP_X ; skips negative jump
NEGX ; JUMPS IF NEGATIVE
JSR NEGATIVE_X
SKIP_X

; Y COORDINATE
ADD R1 R1 #0
BRn NEGY ;CHECKS IF NEGATIVE
JSR POSITIVE_Y
BRnzp SKIP_Y ; skips negative jump
NEGY ; JUMPS IF NEGATIVE
JSR NEGATIVE_Y
SKIP_Y

; Z COORDINATE
ADD R2 R2 #0
BRn NEGZ ;CHECKS IF NEGATIVE
JSR POSITIVE_Z
BRnzp SKIP_Z ; skips negative jump
NEGZ ; JUMPS IF NEGATIVE
JSR NEGATIVE_Z
SKIP_Z

;CHECKS X COOR
ADD R0 R0 #0
BRn NEGX_B ;CHECKS IF NEGATIVE
JSR POSITIVE_X_B
BRnzp SKIP_X_B ; skips negative jump
NEGX_B ; JUMPS IF NEGATIVE
JSR NEGATIVE_X_B
SKIP_X_B

; Y COORDINATE
ADD R1 R1 #0
BRn NEGY_B ;CHECKS IF NEGATIVE
JSR POSITIVE_Y_B
BRnzp SKIP_Y_B ; skips negative jump
NEGY_B ; JUMPS IF NEGATIVE
JSR NEGATIVE_Y_B
SKIP_Y_B

; Z COORDINATE
ADD R2 R2 #0
BRn NEGZ_B ;CHECKS IF NEGATIVE
JSR POSITIVE_Z_B
BRnzp SKIP_Z_B ; skips negative jump
NEGZ_B ; JUMPS IF NEGATIVE
JSR NEGATIVE_Z_B
SKIP_Z_B


;CLEARING REG
AND R4 R4 #0
TRAP 0x27
; changing to negative to minus
NOT R6 R6
ADD R6 R6 #1

; seeing which is bigger
ADD R4 R5 R6 ; r5 is A DIFFERENCE r6 is B difference, if its negative r5 A has a bigger difference therefore B (r6) is closer

BRp B_BIG
BRn A_BIG
BRz ZERO
HALT

A_BIG
AND R0 R0 #0
LEA R0 A_BIGGER
TRAP 0x28
HALT

B_BIG
AND R0 R0 #0
LEA R0 B_BIGGER
TRAP 0x28
HALT

ZERO 
AND R0 R0 #0
LEA R0 EQUAL
TRAP 0x28
HALT

NEGATIVE_X
; R3 IS COORDINATE
LD R3 A_X 
; changing to negative
NOT R3 R3
ADD R3 R3 #1 
ADD R4 R0 R3  ; TWO NEGATIVES 
;CHANGING DIFFERENCE TO POSITIVE
BRp NEGATIVE_SKIP_X_A_
NOT R4 R4 
ADD R4 R4 #1
BRp NEGATIVE_SKIP_X_A_
ADD R5 R5 R4 
;RESET
AND R4 R4 #0
AND R3 R3 #0  
RET

POSITIVE_X 
LD R3 A_X
NOT R3 R3
ADD R3 R3 #1
ADD R4 R0 R3
BRp POSITIVE_X_SKIP ; IF ANSWER IS POSITIVE BECAUSE COORDINATE WAS SMALLER POSITIVE THAN PLAYER X OR WAS NEGATIVE
; COORDINATE WAS BIGGER THEN PLAYER X
NOT R4 R4
ADD R4 R4 #1
POSITIVE_X_SKIP ; SKIPS 
ADD R5 R5 R4
;RESETS
AND R4 R4 #0 
AND R3 R3 #0
RET

; Y AXIS 
NEGATIVE_Y ; JUMP
; R3 IS COORDINATE
LD R3 A_Y 
; changing to negative
NOT R3 R3
ADD R3 R3 #1 
ADD R4 R1 R3  ; TWO NEGATIVES 
;CHANGING DIFFERENCE TO POSITIVE
BRp NEGATIVE_SKIP_Y_A
NOT R4 R4 
ADD R4 R4 #1
NEGATIVE_SKIP_Y_A
ADD R5 R5 R4 
;RESET
AND R4 R4 #0
AND R3 R3 #0 
RET

POSITIVE_Y
LD R3 A_Y
NOT R3 R3
ADD R3 R3 #1
ADD R4 R1 R3
BRp POSITIVE_Y_SKIP ; IF ANSWER IS POSITIVE BECAUSE COORDINATE WAS SMALLER POSITIVE THAN PLAYER X OR WAS NEGATIVE
; COORDINATE WAS BIGGER THEN PLAYER X
NOT R4 R4
ADD R4 R4 #1
POSITIVE_Y_SKIP ; SKIPS 
ADD R5 R5 R4
;RESETS
AND R4 R4 #0 
AND R3 R3 #0
RET

; Z AXIS 
NEGATIVE_Z ; JUMP
; R3 IS COORDINATE
LD R3 A_Z 
; changing to negative
NOT R3 R3
ADD R3 R3 #1 
ADD R4 R2 R3  ; TWO NEGATIVES 
;CHANGING DIFFERENCE TO POSITIVE
BRp NEGATIVE_SKIP_Z_A
NOT R4 R4 
ADD R4 R4 #1
NEGATIVE_SKIP_Z_A
ADD R5 R5 R4 
;RESET
AND R4 R4 #0
AND R3 R3 #0 
RET

POSITIVE_Z ; JMP
LD R3 A_Z
NOT R3 R3
ADD R3 R3 #1
ADD R4 R2 R3
BRp POSITIVE_Z_SKIP ; IF ANSWER IS POSITIVE BECAUSE COORDINATE WAS SMALLER POSITIVE THAN PLAYER X OR WAS NEGATIVE
; COORDINATE WAS BIGGER THEN PLAYER X
NOT R4 R4
ADD R4 R4 #1
POSITIVE_Z_SKIP ; SKIPS 
ADD R5 R5 R4
;RESETS
AND R4 R4 #0 
AND R3 R3 #0
RET

; B
NEGATIVE_X_B ; JUMP
; R3 IS COORDINATE
LD R3 B_X 
; changing to negative
NOT R3 R3
ADD R3 R3 #1 
ADD R4 R0 R3  ; TWO NEGATIVES 
;CHANGING DIFFERENCE TO POSITIVE
BRp NEGATIVE_SKIP_X_B
NOT R4 R4 
ADD R4 R4 #1
NEGATIVE_SKIP_X_B
ADD R6 R6 R4 
;RESET
AND R4 R4 #0
AND R3 R3 #0 
RET

POSITIVE_X_B
LD R3 B_X
NOT R3 R3
ADD R3 R3 #1
ADD R4 R0 R3
BRp POSITIVE_X_SKIP_B ; IF ANSWER IS POSITIVE BECAUSE COORDINATE WAS SMALLER POSITIVE THAN PLAYER X OR WAS NEGATIVE
; COORDINATE WAS BIGGER THEN PLAYER X
NOT R4 R4
ADD R4 R4 #1
POSITIVE_X_SKIP_B ; SKIPS 
ADD R6 R6 R4
;RESETS
AND R4 R4 #0 
AND R3 R3 #0
RET

; Y AXIS 
NEGATIVE_Y_B 
; R3 IS COORDINATE
LD R3 B_Y 
; changing to negative
NOT R3 R3
ADD R3 R3 #1 
ADD R4 R1 R3  ; TWO NEGATIVES 
;CHANGING DIFFERENCE TO POSITIVE
BRp NEGATIVE_SKIP_Y_B
NOT R4 R4 
ADD R4 R4 #1
NEGATIVE_SKIP_Y_B
ADD R6 R6 R4 
;RESET
AND R4 R4 #0
AND R3 R3 #0 
RET

POSITIVE_Y_B ; JMP
LD R3 B_Y
NOT R3 R3
ADD R3 R3 #1
ADD R4 R1 R3
BRp POSITIVE_Y_SKIP_B ; IF ANSWER IS POSITIVE BECAUSE COORDINATE WAS SMALLER POSITIVE THAN PLAYER X OR WAS NEGATIVE
; COORDINATE WAS BIGGER THEN PLAYER X
NOT R4 R4
ADD R4 R4 #1
POSITIVE_Y_SKIP_B ; SKIPS 
ADD R6 R6 R4
;RESETS
AND R4 R4 #0 
AND R3 R3 #0
RET

; Z AXIS 
NEGATIVE_Z_B ; JUMP
; R3 IS COORDINATE
LD R3 B_Z 
; changing to negative
NOT R3 R3
ADD R3 R3 #1 
ADD R4 R2 R3  ; TWO NEGATIVES 
;CHANGING DIFFERENCE TO POSITIVE
BRp NEGATIVE_SKIP_Z_B
NOT R4 R4 
ADD R4 R4 #1
NEGATIVE_SKIP_Z_B
ADD R6 R6 R4 
;RESET
AND R4 R4 #0
AND R3 R3 #0 
RET

POSITIVE_Z_B ; JMP
LD R3 B_Z
NOT R3 R3
ADD R3 R3 #1
ADD R4 R2 R3
BRp POSITIVE_Z_SKIP_B ; IF ANSWER IS POSITIVE BECAUSE COORDINATE WAS SMALLER POSITIVE THAN PLAYER X OR WAS NEGATIVE
; COORDINATE WAS BIGGER THEN PLAYER X
NOT R4 R4
ADD R4 R4 #1
POSITIVE_Z_SKIP_B ; SKIPS 
ADD R6 R6 R4
;RESETS
AND R4 R4 #0 
AND R3 R3 #0
RET

A_X .FILL #1
A_Y .FILL #2
A_Z .FILL #3
B_X .FILL #20
B_Y .FILL #32
B_Z .FILL #-8
A_BIGGER .STRINGZ "The player is closer to point A"
B_BIGGER .STRINGZ	"The player is closer to point B"
EQUAL .STRINGZ "The player is equally far from both points"
.END