.ORIG x3000
TRAP 0x29 ; PLAYER COORD
TRAP 0x2D ; MAX HEIGHT OF BLOCK, R1
ADD R4 R4 R1 ; TO HOLD H VALUE
; ADD DIFFERENT X AND Z COORDINATES TO GET TO 9 X 9 SQUARES 
ADD R2 R2 #1 ; right 1 z 
JSR PILLAR 
ADD R2 R2 #-2 ; left -1z
JSR PILLAR
ADD R2 R2 #1 ; RESET TO MIDDLE
ADD R0 R0 #1 ; GOES UP
JSR PILLAR 
ADD R2 R2 #1 ; RIGHT
JSR PILLAR
ADD R2 R2 #-2 ; LEFT
JSR PILLAR ; TOP BAR DONE
ADD R2 R2 #1 ; RESET TO MIDDLE
ADD R0 R0 #-2 ; GOES BOTTOM
JSR PILLAR ; BOTTOM MIDDLE
ADD R2 R2 #1 
JSR PILLAR ; BOTTOM RIGHT
ADD R2 R2 #-2
JSR PILLAR ; BOTTOM LEFT
ADD R2 R2 #1 ; RESET

HALT

PILLAR
 TRAP 0x2D ; GET CURRENT HEIGHT 
 NOT R5 R1 ; height in a negative 
 ADD R5 R5 #1
 ADD R5 R4 R5 ; CONTAINS DIFFERENECE FROM MIDDLE MIDDLE HEIGHT AND CURRENT BLOCK HEIGHT
TRAP 0x27
 BRp BUILD
 BRn CUT 
 BRz END

BUILD 
;idk
BUILD_LOOP
 TRAP 0x2B ; GET BLOCKID R3 NOW HOLDS VALUE
 ADD R3 R3 #-1 ; CHECKS IF BLOCK ID IS AIR
 BRzp NOT_AIR_START
 AND R3 R3 #0
 ADD R3 R3 #4
 TRAP 0x2C
 NOT_AIR_START
 AND R3 R3 #0
 ADD R1 R1 #1 ; GOES UP IN HEIGHT
 ADD R5 R5 #-1 ; MINUS COUNT
BRp BUILD_LOOP
RET

CUT
 AND R3 R3 #0 ; TO MAKE BLOCKID AIR
CUT_LOOP
; STARTING FROM R1 BEING AT H EVERYTHING BELOW AIR TILL H IS REACHED WITH COUNT
TRAP 0x2C ; SETS AIR BLOCK
ADD R1 R1 #-1 ; MOVES DOWN A HEIGHT BLOCK
ADD R5 R5 #1 ; minus counter
BRn CUT_LOOP
RET

END 
RET
.END