.ORIG x3000
TRAP 0x29 ; player position, r0,r1,r2
STI R1 Y_VALUE; KEEPING PLAYER Y VALUE
ADD R3 R3 R1 ; FOR DIFFERENCE
TRAP 0x27
TRAP 0x2D ; gets height of block, new r2

NOT R4 R1 
ADD R4 R4 #1
; POSITIVE DIFFIERENCE IN Y VALUES
ADD R4 R3 R4

; RESET 
AND R3 R3 #0

FOR LOOP 
ADD R5 R5 #3

HEIGHT_LOOP
;CHECKS 9 BLOCKS
JSR BLOCKS
ADD R0 R0 #-1
JSR BLOCKS
ADD R0 R0 #2
JSR BLOCKS
; RESETS X TRUE VALUE
ADD R0 R0 #-1

ADD R1 R1 #1 ; NEXT HEIGHT BLOCK
ADD R4 R4 #-1 ; MINUS DIFFERENCE UNTIL PLAYER HEIGHT IS REACHED
BRz HEIGHT_LOOP

; BLOCKS

; TRAP 0x2B ; GET BLOCKID R3 NOW HOLDS VALUE
; ADD R3 R3 #-1 ; CHECKS IF BLOCK ID IS AIR
; BRzp NOT_AIR_START
; AND R3 R3 #0
; ADD R3 R3 #4
; TRAP 0x2C
; NOT_AIR_START
; ADD R2 R2 #-1 ; LEFT Z BLOCK

; TRAP 0x2B ; GET BLOCKID R3 NOW HOLDS VALUE
; ADD R3 R3 #-1 ; CHECKS IF BLOCK ID IS AIR
; BRzp NOT_AIR_LEFT
; AND R3 R3 #0
; ADD R3 R3 #4
; TRAP 0x2C
; NOT_AIR_LEFT

; ADD R2 R2 #2  ; RIGHT Z BLOCK
; TRAP 0x2B ; GET BLOCKID R3 NOW HOLDS VALUE
; ADD R3 R3 #-1 ; CHECKS IF BLOCK ID IS AIR
; BRzp NOT_AIR_RIGHT
; AND R3 R3 #0
; ADD R3 R3 #4 ; SET R3 TO COBBLESTONE ID
; TRAP 0x2C
; NOT_AIR_RIGHT

; RESET 
; ADD R2 R2 #-1
;RET

HALT
Y_VALUE .FILL X3250
.END