.ORIG x3000
TRAP 0x29 ; get player position

;CHECKS X COOR
LD R3 A_X
ADD R0 R0 #0
BRn NEGX ;CHECKS IF NEGATIVE
JSR POSITIVE
BRnzp SKIP_X ; skips negative jump
NEGX ; JUMPS IF NEGATIVE
JSR NEGATIVE
SKIP_X

; Y COORDINATE
LD R3 A_Y
ADD R1 R1 #0
BRn NEGY ;CHECKS IF NEGATIVE
JSR POSITIVE
BRnzp SKIP_Y ; skips negative jump
NEGY ; JUMPS IF NEGATIVE
JSR NEGATIVE
SKIP_Y

; Z COORDINATE
LD R3 A_Z
ADD R2 R2 #0
BRn NEGZ ;CHECKS IF NEGATIVE
JSR POSITIVE
BRnzp SKIP_Z ; skips negative jump
NEGZ ; JUMPS IF NEGATIVE
JSR NEGATIVE
SKIP_Z

ST R5 A_DIFF
AND R5 R5 #0

;CHECKS X COOR
LD R3 B_X
ADD R0 R0 #0
BRn NEGX_B ;CHECKS IF NEGATIVE
JSR POSITIVE
BRnzp SKIP_X_B ; skips negative jump
NEGX_B ; JUMPS IF NEGATIVE
JSR NEGATIVE
SKIP_X_B

; Y COORDINATE
LD R3 B_Y
ADD R1 R1 #0
BRn NEGY_B ;CHECKS IF NEGATIVE
JSR POSITIVE_Y_B
BRnzp SKIP_Y_B ; skips negative jump
NEGY_B ; JUMPS IF NEGATIVE
JSR NEGATIVE_Y_B
SKIP_Y_B

; Z COORDINATE
LD R3 B_Z
ADD R2 R2 #0
BRn NEGZ_B ;CHECKS IF NEGATIVE
JSR POSITIVE
BRnzp SKIP_Z_B ; skips negative jump
NEGZ_B ; JUMPS IF NEGATIVE
JSR NEGATIVE
SKIP_Z_B


;CLEARING REG
AND R4 R4 #0
TRAP 0x27
; changing to negative to minus
AND R6 R6 #0
ADD R6 R6 R5
AND R5 R5 #0
LD R5 A_DIFF
NOT R6 R6
ADD R6 R6 #1

; seeing which is bigger
ADD R4 R5 R6 ; r5 is A DIFFERENCE r6 is B difference, if its negative r5 A has a bigger difference therefore B (r6) is closer

BRp B_BIG
BRn A_BIG
BRz ZERO
HALT

A_BIG
AND R0 R0 #0
LEA R0 A_BIGGER
TRAP 0x28
HALT

B_BIG
AND R0 R0 #0
LEA R0 B_BIGGER
TRAP 0x28
HALT

ZERO 
AND R0 R0 #0
LEA R0 EQUAL
TRAP 0x28
HALT

NEGATIVE
; changing to negative
NOT R3 R3
ADD R3 R3 #1 
ADD R4 R0 R3  ; TWO NEGATIVES 
BRp NEGATIVE_SKIP_X_A
NOT R4 R4 
ADD R4 R4 #1
NEGATIVE_SKIP_X_A
ADD R5 R5 R4 
;RESET
AND R4 R4 #0
AND R3 R3 #0  
RET

POSITIVE 
NOT R3 R3
ADD R3 R3 #1
ADD R4 R0 R3
BRp POSITIVE_X_SKIP ; IF ANSWER IS POSITIVE BECAUSE COORDINATE WAS SMALLER POSITIVE THAN PLAYER X OR WAS NEGATIVE
; COORDINATE WAS BIGGER THEN PLAYER X
NOT R4 R4
ADD R4 R4 #1
POSITIVE_X_SKIP ; SKIPS 
ADD R5 R5 R4
;RESETS
AND R4 R4 #0 
AND R3 R3 #0
RET

A_DIFF .FILL x3200
A_X .FILL #1
A_Y .FILL #2
A_Z .FILL #3
B_X .FILL #20
B_Y .FILL #32
B_Z .FILL #-8
A_BIGGER .STRINGZ "The player is closer to point A"
B_BIGGER .STRINGZ	"The player is closer to point B"
EQUAL .STRINGZ "The player is equally far from both points"
.END